import fly from "@/utils/request";

const api = {
  queryMemberUpgradeInfo: (r: any) => fly.post('/api/member/queryMemberUpgradeInfo.json', r),
  membercardInterestDesc: (r: any) => fly.get('/api/member/membercardInterestDesc.json', r),
  orderAggregation: (r: any) => fly.get("/api/orderAggregation/orderList.json", r),
  hotelInfo: (r: any) => fly.get("/api/hotel/info.json", r),
  pay: (r: any) => fly.get("/api/pay/pay.json", r),
  showOrder: (r: any) => fly.get("/api/hotel/product/showOrder.json", r),
  getCancelRule: (r: any) => fly.post(" /api/wxMiniApp/getCancelRule.json?" + r),
  findCouponDetailListByCondi: (r: any) => fly.get("/api/member/findCouponDetailListByCondi.json", r),
  resrvCheck: (r: any) => fly.post("/api/hotel/product/resrvCheck.json?appid=" + r.appid + "&componentAppid=" + r.componentAppid, r),
  makeOrder: (r: any) => fly.post("/api/hotel/product/makeOrder.json?appid=" + r.appid + "&componentAppid=" + r.componentAppid, r),
  deleteGoodsCollection: (r: any) => fly.post('/api/shop/deleteGoodsCollection.json', r),
  getGoodsIsCollection: (r: any) => fly.get('/api/shop/getGoodsIsCollection.json', r),
  addGoodsCollection: (r: any) => fly.post('/api/shop/addGoodsCollection.json', r),
  findHotel: (r: any) => fly.post("/api/hotel/findHotelByCondition.json?appid=" + r.appid + "&componentAppid=" + r.componentAppid, r),
  updateUserinfoByMiniOpenId: (r: any) => fly.post('/api/wxMiniApp/updateUserinfoByMiniOpenId.json', r),
  listAccount: (r: any) => fly.get(" /api/member/listAccount.json", r),
  listPointByMemberId: (r: any) => fly.get("/api/member/listPointByMemberId.json", r),
  queryMemberCardByCondition: (r: any) => fly.post("/api/member/queryMemberCardByCondition.json", r),
  bindCardToMember: (r: any) => fly.post("/api/member/bindCardToMember.json", r),
  queryPointsExpiredRemindData: (r: any) => fly.post("/api/member/queryPointsExpiredRemindData.json", r),
  listCouponWithHistoryByCardNo: (r: any) => fly.get("/api/member/listCouponWithHistoryByCardNo.json", r),
  interfaceTransfer: (r: any) => fly.post('/api/sync/interfaceTransfer', r),
  getMultiSysOptionCommon: (r: any) => fly.get("/api/cache/sysOptions/getMultiSysOptionCommon.json", r),
  removeOpenId: (r: any) => fly.post("/api/member/removeOpenId.json?" + r, r),
  getShopButtonConfig: (r: any) => fly.get('/api/shop/getShopButtonConfig.json', r),
  getShopMemberCenterConfig: (r: any) => fly.get("/api/shop/getShopMemberCenterConfig", r),
  hotelListAll: (r: any) => fly.post("/api/hotel/hotelListAllNew.json?appid=" + r.appid + "&componentAppid=" + r.componentAppid, r),
  advertisementPage: (r: any) => fly.get("/shopapi/sz/advertisementPage", r),
  threeMetaCheck: (r: any) => fly.post("/api/member/threeMetaCheck.json", r),
  listPoint: (r: any) => fly.get("/api/member/listPoint.json", r),
  getScrollPic: (r: any) => fly.get("/api/shop/getScrollPic.json", r),
  getWxCode: (r: any) => fly.get("/api/microSoftWare/getOpenidSessionKey.json", r),
  decrypt: (r: any) => fly.get("/api/wxMiniApp/decrypt.json", r),
  memberLoginByMobileAndOpenId: (r: any) => fly.get("/api/member/memberLoginByMobileAndOpenId.json", r),
  update: (r: any) => fly.post("/api/member/updateMemberBaseInfo.json?hotelGroupId=" + r.hotelGroupId, r),
  memberLoginOpen: (r: any) => fly.get("/api/member/memberLoginOpen.json", r),
  verifyCode: (r: any) => fly.get("/api/member/createIdentifyCode.json", r),
  verifyIdentifyCode: (r: any) => fly.get("/api/member/verifyIdentifyCode.json", r),
  memberLoginByMobileCode: (r: any) => fly.post("/api/member/memberLoginByMobileCode.json?" + r.url),
  fastRegister: (r: any) => fly.post("/api/member/fastRegister.json?" + r.url),
  updateMemberInfoForWeiXin: (r: any) => fly.post("/api/member/updateMemberInfoForWeiXin.json", r),
  bindOpenId: (r: any) => fly.get("/api/member/bindOpenId.json", r),
  marketingPage: (r: any) => fly.post("/shopapi/sz/marketingPage", r),
  travelProductList: (r: any) => fly.post("/shopapi/sz/travelProductList", r),
  modePage: (r: any) => fly.post("/shopapi/sz/modePage", r),
  listTravelDictionary: (r: any) => fly.post("/shopapi/marketingActivityPage/listTravelDictionary", r),
  getGoodsCollection: (r: any) => fly.get("/api/shop/getGoodsCollection.json", r),
  listGuestLinkExtraInfoWithMemberIdOrOpenId: (r: any) => fly.post("/memberapi/guestBase/listGuestLinkExtraInfoWithMemberIdOrOpenId", r),
  saveGuestBase: (r: any) => fly.post("/memberapi/guestBase/saveGuestBase", r),
  updateGuestBase: (r: any) => fly.post("/memberapi/guestBase/updateGuestBase", r),
  deleteGuestLinkRelation: (r: any) => fly.post("/memberapi/guestBase/deleteGuestLinkRelation", r),
  saveOrder: (r: any) => fly.post("/api/travel/saveOrder", r),
  orderDetail: (r: any) => fly.get("/api/travel/orderDetail", r),
  travelPay: (r: any) => fly.post("/api/travel/pay.json", r),
  invokeExtSign: (r: any) => fly.get("/api/fdd/invokeExtSign.json", r),
  goodsDetail: (r: any) => fly.get('/api/shop/goodsDetail.json', r),
  goodsSku: (r: any) => fly.get('/api/shop/goodsSku.json', r),
  submitOrder: (r: any) => fly.post('/api/shop/submitOrder.json', r),
  shopOrderDetail: (r: any) => fly.get("/api/shop/orderDetail.json", r),
  shopPay: (r: any) => fly.post("/api/shop/pay.json", r),
};

export default api;