import fly from "@/utils/request";

const api = {
  findCouponDetailListByCouponNo: (r: any) => fly.get("/api/member/findCouponDetailListByCouponNo.json", r),
  getAllCardLevel: (r: any) => fly.get("/api/member/getAllCardLevel.json", r),
  shopOrderListSearch: (r: any) => fly.post("/memberapi/weiMobCloudShopOrder/shopOrderListSearch", r),
  getUserAvailableCardList: (r: any) => fly.get("/memberapi/weiMobCloudCard/getUserAvailableCardList", r),
  xhsPay: (r: any) => fly.post("/redminiapi/deal/query_pay_token", r),
  cmbchinaUserDataDes: (r: any) => fly.post("/api/tfMember/userDataDes.json", r),
  cmbchinaGetAuthInfo: (r: any) => fly.get("/api/tfMember/getAuthInfo.json", r),
  getOrderInvoiceSta: (r: any) => fly.get("/api/invoice/getOrderInvoiceSta.json", r),
  refreshMemberInfo: (r: any) => fly.get("/api/member/refreshMemberInfo.json", r),
  bindCouponToMemberForPlatform: (r: any) => fly.get("/api/coupon/bindCouponToMemberForPlatform.json", r),
  isUpdateMemberBaseInfo: (r: any) => fly.post("/api/member/isUpdateMemberBaseInfo.json", r),
  queryMemberUpgradeInfo: (r: any) => fly.post('/api/member/queryMemberUpgradeInfo.json', r),
  membercardInterestDesc: (r: any) => fly.get('/api/member/membercardInterestDesc.json', r),
  orderAggregation: (r: any) => fly.get("/api/orderAggregation/orderList.json", r),
  hotelInfo: (r: any) => fly.get("/api/hotel/info.json", r),
  pay: (r: any) => fly.get("/api/pay/pay.json", r),
  showOrder: (r: any) => fly.get("/api/hotel/product/showOrder.json", r),
  getCancelRule: (r: any) => fly.post("/api/wxMiniApp/getCancelRule.json?" + r),
  findCouponDetailListByCondi: (r: any) => fly.get("/api/member/findCouponDetailListByCondi.json", r),
  resrvCheck: (r: any) => fly.post("/api/hotel/product/resrvCheck.json?appid=" + r.appid + "&componentAppid=" + r.componentAppid, r),
  makeOrder: (r: any) => fly.post("/api/hotel/product/makeOrder.json?appid=" + r.appid + "&componentAppid=" + r.componentAppid, r),
  deleteGoodsCollection: (r: any) => fly.post('/api/shop/deleteGoodsCollection.json', r),
  getGoodsIsCollection: (r: any) => fly.get('/api/shop/getGoodsIsCollection.json', r),
  addGoodsCollection: (r: any) => fly.post('/api/shop/addGoodsCollection.json', r),
  findHotel: (r: any) => fly.post("/api/hotel/findHotelByCondition.json?appid=" + r.appid + "&componentAppid=" + r.componentAppid, r),
  updateUserinfoByMiniOpenId: (r: any) => fly.post('/api/wxMiniApp/updateUserinfoByMiniOpenId.json', r),
  listAccount: (r: any) => fly.get("/api/member/getAccountIncludeTreatList.json", r),
  listPointByMemberId: (r: any) => fly.get("/api/member/listPointByMemberId.json", r),
  queryMemberCardByCondition: (r: any) => fly.post("/api/member/queryMemberCardByCondition.json", r),
  bindCardToMember: (r: any) => fly.post("/api/member/bindCardToMember.json", r),
  queryPointsExpiredRemindData: (r: any) => fly.post("/api/member/queryPointsExpiredRemindData.json", r),
  listCouponWithHistoryByCardNo: (r: any) => fly.get("/api/member/listCouponWithHistoryByCardNo.json", r),
  interfaceTransfer: (r: any) => fly.post('/api/sync/interfaceTransfer', r),
  getMultiSysOptionCommon: (r: any) => fly.get("/api/cache/sysOptions/getMultiSysOptionCommon.json", r),
  removeOpenId: (r: any) => fly.post("/api/member/removeOpenId.json?" + r, r),
  getShopButtonConfig: (r: any) => fly.get('/api/shop/getShopButtonConfig.json', r),
  getShopMemberCenterConfig: (r: any) => fly.get("/api/shop/getShopMemberCenterConfig", r),
  hotelListAll: (r: any) => fly.post("/api/hotel/hotelListAllNew.json?appid=" + r.appid + "&componentAppid=" + r.componentAppid, r),
  advertisementPage: (r: any) => fly.get("/shopapi/sz/advertisementPage", r),
  threeMetaCheck: (r: any) => fly.post("/api/member/threeMetaCheck.json", r),
  listPoint: (r: any) => fly.get("/api/member/listPoint.json", r),
  getScrollPic: (r: any) => fly.get("/api/shop/getScrollPic.json", r),
  getWxCode: (r: any) => fly.post("/api/microSoftWare/getOpenidSessionKeyV2.json", r),
  decrypt: (r: any) => fly.post("/api/wxMiniApp/decryptV2.json", r),
  memberLoginByMobileAndOpenId: (r: any) => fly.get("/api/member/memberLoginByMobileAndOpenId.json", r),
  update: (r: any) => fly.post("/api/member/updateMemberBaseInfo.json?hotelGroupId=" + r.hotelGroupId, r),
  memberLoginOpen: (r: any) => fly.get("/api/member/memberLoginOpen.json", r),
  verifyCode: (r: any) => fly.get("/api/member/createIdentifyCode.json", r),
  verifyIdentifyCode: (r: any) => fly.get("/api/member/verifyIdentifyCode.json", r),
  memberLoginByMobileCode: (r: any) => fly.post("/api/member/memberLoginByMobileCode.json?" + r.url),
  fastRegister: (r: any) => fly.post("/api/member/fastRegister.json?" + r.url),
  updateMemberInfoForWeiXin: (r: any) => fly.post("/api/member/updateMemberInfoForWeiXin.json", r),
  bindOpenId: (r: any) => fly.get("/api/member/bindOpenId.json", r),
  marketingPage: (r: any) => fly.post("/shopapi/sz/marketingPage", r),
  travelProductList: (r: any) => fly.post("/shopapi/sz/travelProductList", r),
  modePage: (r: any) => fly.post("/shopapi/sz/modePage", r),
  listTravelDictionary: (r: any) => fly.post("/shopapi/marketingActivityPage/listTravelDictionary", r),
  getGoodsCollection: (r: any) => fly.get("/api/shop/getGoodsCollection.json", r),
  listGuestLinkExtraInfoWithMemberIdOrOpenId: (r: any) => fly.post("/memberapi/guestBase/listGuestLinkExtraInfoWithMemberIdOrOpenId", r),
  saveGuestBase: (r: any) => fly.post("/memberapi/guestBase/saveGuestBase", r),
  updateGuestBase: (r: any) => fly.post("/memberapi/guestBase/updateGuestBase", r),
  deleteGuestLinkRelation: (r: any) => fly.post("/memberapi/guestBase/deleteGuestLinkRelation", r),
  saveOrder: (r: any) => fly.post("/api/travel/saveOrder", r),
  orderDetail: (r: any) => fly.get("/api/travel/orderDetail", r),
  activityOrder: (r: any) => fly.get("/api/singleActivity/querySingleActivityOrder", r),
  marketingActivityPage: (r: any) => fly.post("/shopapi/sz/marketingActivityPage", r),
  listMarketingProducts: (r: any) => fly.get("/shopapi/marketingActivity/listMarketingProducts", r),
  pageHotelListForApp: (r: any) => fly.get("/hotelapi/aggregateProductList/pageHotelListForApp", r),
  shopGoodsPage: (r: any) => fly.get("/shopapi/sz/shopGoodsPage", r),
  travelPay: (r: any) => fly.post("/api/travel/pay.json", r),
  activityPay: (r: any) => fly.post("/api/singleActivity/pay", r),
  invokeExtSign: (r: any) => fly.get("/api/fdd/invokeExtSign.json", r),
  prizewinner: (r: any) => fly.get("/api/wechat/platform/game/prizewinner.json", r),
  rewardlist: (r: any) => fly.get("/api/wechat/platform/game/rewardlist", r),
  savePrizeAddress: (r: any) => fly.get("/api/wechat/platform/game/savePrizeAddress.json", r),
  getBaiduAk: (r: any) => fly.get("/service/BaiduApi/baiduAk", r),
  goodsDetail: (r: any) => fly.get('/api/shop/goodsDetail.json', r),
  goodsSku: (r: any) => fly.get('/api/shop/goodsSku.json', r),
  addAddress: (r: any) => fly.post("/api/member/shippingAddress.json", r),// 地址管理
  getMemberAddress: (r: any) => fly.get("/api/member/shippingAddress.json", r),//地址列表
  deleteAddress: (r: any) => fly.delete("/api/member/shippingAddress.json?id=" + r.id + "&memberId=" + r.memberId),
  saveOrUpdateMemberInvoice: (r: any) => fly.post("/api/member/saveOrUpdateMemberInvoice.json", r),
  //获取发票信息
  memberInvoice: (r: any) => fly.get("/api/member/memberInvoice.json", r),
  submitOrder: (r: any) => fly.post('/api/shop/submitOrder.json', r),
  shopOrderDetail: (r: any) => fly.get("/api/shop/orderDetail.json", r),
  shopPay: (r: any) => fly.post("/api/shop/pay.json", r),
  applyInvoice: (r: any) => fly.get("/api/invoice/applyInvoice.json", r),
  activityTaskList: (r: any) => fly.post('/activityapi/tasketCenter/selectMarketTaskCentersH5', r),
  listRootCategory: (r: any) => fly.get("/api/albumCategory/listRootCategory", r),
  msgPage: (r: any) => fly.post("/shopapi/sz/msgPage", r),
  getWxacodeUnlimitUrl: (r: any) => fly.get("/api/microSoftWare/admin/getWxacodeUnlimitUrl.json", r),
  listGoods: (r: any) => fly.get('/api/shop/listGoods.json', r),
  saveActivityOrder: (r: any) => fly.post("/api/singleActivity/saveSingleActivityOrder", r),
  deliveryMessageItemAjax: (r: any) => fly.get('/api/shop/deliveryMessageItemAjax.json', r),//物流查询
  getCanReceivedListNew: (r: any) => fly.get('/api/shop/getCanReceivedListNew.json', r),
  receiveSCCouponNew: (params: any) => fly.post('/api/shop/receiveSCCouponNew', params, {
    'Content-Type': 'application/x-www-form-urlencoded'
  }),
  receiveSCCouponNewTransfer: (r: any) => fly.post('/api/shop/receiveSCCouponNewTransfer', r),
  getDiscountOfMember: (r: any) => fly.post('/api/distribution/getDiscountOfMember.json', r),
  getPayDetail: (r: any) => fly.get("/api/singleActivity/payDetail", r),
  cancelSingleActivityOrder: (r: any) => fly.get("/api/singleActivity/cancelSingleActivityOrder", r),
  saveOrUpdateOrderInvoice: (r: any) => fly.get("/api/invoice/saveOrUpdateOrderInvoice.json", r),
  getInvoiceOrder: (r: any) =>fly.get("/api/invoice/getInvoiceOrder.json", r),
  shopGoodsTemplate: (r:any) => fly.get('/api/shop/shopGoodsTemplate.json', r),
  queryMarketingProducts: (r:any) => fly.post('/shopapi/marketingActivity/listMarketingProductsByCodes', r),
  deleteMemberInvoice: (r: any) => fly.get("/api/member/deleteMemberInvoice.json", r),
  selectInvitationSpoilRules: (r: any) => fly.post("/activityapi/InvitationSpoil/selectInvitationSpoilRules", r),
  downloadContractNoByGcRsvNo: (r: any) => fly.get("/api/fdd/downloadContractNoByGcRsvNo.json", r),
  getContractNoByGcRsvNo: (r: any) => fly.get("/api/fdd/getContractNoByGcRsvNo.json", r),
  guestCheck: (r: any) => fly.post("/api/selfBook/guestCheck.json", r),
  queryProductsByMarketingTags: (r: any) => fly.get("/shopapi/sz/queryProductsByMarketingTags.json", r),
  queryMarketingPageTags: (r: any) => fly.get("/shopapi/sz/queryMarketingPageTags.json", r),
  mapSysDic: (r: any) => fly.get("/rsapi/rhkMiniapp/mapSysDic", r),
  createServerOrder: (r: any) => fly.post("/rsapi/rsOrder/createServerOrderV2", r),
  getListHotelService: (r: any) => fly.get("/hotelapi/hotelServiceManage/listHotelServiceBySta", r),
  saveRecomm: (r: any) => fly.post("/rsapi/rhkMiniapp/saveRecommV2", r),
  updateOrder: (r: any) => fly.post("/rsapi/rsOrder/updateOrder", r),
  updateInstantRsOrder: (r: any) => fly.post(`/rsapi/rsIsOrder/updateInstantRsOrder`, r),
  orderList: (r: any) => fly.post("/rsapi/rsOrder/list", r),
  checkPointCustomize: (r: any) => fly.post("/hotelapi/MapModeConfig/checkPointCustomize", r),
  listHotelServiceBySta: (r: any) => fly.get("/hotelapi/hotelServiceManage/listHotelServiceBySta", r),
  queryUserInfo: (r: any) => fly.get("/rsapi/rsDuty/queryUserInfo", r),
  // 通过场景值取的参数
  getWxacodeParams: (r: any) => fly.get("/api/shop/getWxacodeParams.json", r),
  checkWhitelist: (r: any) => fly.get("/api/marketingActivity/whitelist/checkWhitelist", r),
  batchQueryShopConfig: (r: any) =>fly.get("/api/shop/batchQueryShopConfig.json", r),
  getInvoiceAmountAndMsg: (r: any) => fly.get("/api/invoice/getInvoiceAmountAndMsg.json", r),
  getAvailableCoupon: (r:any) => fly.post('/api/shop/getAvailableCoupon?hotelGroupCode=' + r.hotelGroupCode + '&hotelGroupId=' + r.hotelGroupId, r),
  weimoInterfaceTransfer: (r: any) => fly.post('/shopapi/weimobCloud/interfaceTransfer', r),
  saveInvitationYQHYRecord: (r: any) => fly.post('/activityapi/InvitationSpoil/saveInvitationYQHYRecord', r),//点击立即邀请按钮 生成邀请好友记录接口
  calculatePrice: (r: any) => fly.post('/api/singleActivity/getSingleActivityOrderPrice', r),
  getComplaintAndAdvice: (r: any) => fly.post("/rsapi/frontend/getComplaintAndAdvice", r),
  findInvitationLandConfigByCodeH5: (r) => fly.get('/activityapi/InvitationSpoil/findInvitationLandConfigByCodeH5', r),//查询落地页接口
  getMemberInfoByCardNo: (r) => fly.get('/api/member/getMemberInfoByCardNo', r),//用户信息
  ifCanRewardGiveaways: (r) => fly.post('/activityapi/InvitationSpoil/ifCanRewardGiveaways', r),//被邀请人点击链接进入页面后，是否可以赠送邀请人奖励判断接口
  saveInvitationJSYQRecord: (r) => fly.post('/activityapi/InvitationSpoil/saveInvitationJSYQRecord', r),//点击注册松赞会员保存接受邀请记录接口
};

export default api;